# Generated by Django 2.0.5 on 2018-05-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_suscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
    ]
