# Generated by Django 2.0.5 on 2018-05-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_answer_terminado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='terminado',
        ),
        migrations.AddField(
            model_name='suscription',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
    ]
